---
title: "video game stats"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
runtime: shiny
---

```{r setup, include=FALSE}

#install.packages("flexdashboard")
#install.packages("shiny")
#install.packages("datasets")
library(flexdashboard)
library(shiny)
library(datasets)
#data(faithful)
##
# Authors: Justin Hathaway, Jenkin Schibel, Anthony Moran
##

# Take in our csv file and create a dataframe
games <- read.csv("games.csv", header=TRUE)
data(games)
attach(games)
```

Column {.sidebar}
-----------------------------------------------------------------------

Global video game sales based on consoles based on ESRB rating

```{r}
sales <- c("NA_Sales","EU_Sales","JP_Sales","Other_Sales","Global_Sales")
scores <- c("Critic_Score","User_Score")
score_quantity <- c("Critic_Count","User_Count")
other <- c("Name","Platform","Year_Of_Release","Genre","Publisher")

selectInput("type", label = "global sales display selection based on other attributes", choices = other, selected = "Rating")
selectInput("lm_1", label = "sales comparitor of linear model", choices = sales, selected = "Rating")
selectInput("lm_2", label = "scores selection for linear model", choices = scores, selected = "User_Score")
selectInput("glm_select", label = "sales type for glm model", choices = sales, selected = "Global_Sales")
```

Row
-----------------------------------------------------------------------

###Global Video game sales compares to misc game attributes

```{r}
renderPlot({
 plot(y=Global_Sales,x=eval(as.symbol(input$type)), main="Global Sales", col="blue",ylab="Number of units sold (millions)", xlab=input$type)
  
  })
```

###linear regression model for correlating sales and user or critic scores

```{r}

renderPlot({
 plot(y=eval(as.symbol(input$lm_1)), x=eval(as.symbol(input$lm_2)), main="linear regression", col="blue",ylab="number of units sold in millions", xlab=input$lm_2)
  
 lm.fit = lm(eval(as.symbol((input$lm_1))) ~ eval(as.symbol((input$lm_2))))
 
 abline(lm.fit)
  })
```


###GLM model for showing levels of influence on game sales
```{r}
renderPlot({
     library(gbm)
     data = read.csv("test/Video_Games_Sales_as_at_22_Dec_2016.csv")
     colnames(data)
     clean = data
     clean.omit = na.omit(clean)
     clean.omit = clean.omit[!(clean.omit$NA_Sales > 12),]
     
     clean.omit$Developer = as.numeric(as.factor(clean.omit$Developer))
     
     clean.omit$User_Score = as.numeric(as.character(clean.omit$User_Score))
     
     sample <- sample.int(n = nrow(clean.omit), size = floor(.3*nrow(clean.omit)))
     train <- clean.omit[sample, ]
     test  <- clean.omit[-sample, ]
     
     boost.vg=gbm(eval(as.symbol((input$glm_select))) ~ Genre + Platform + Developer + Publisher + User_Score + Critic_Score, data=clean.omit[-sample,], distribution="gaussian",n.trees=5000,interaction.depth=8)
     
     tree.pred=predict(boost.vg,newdata=clean.omit[sample,],n.trees=5000)
     head(tree.pred)
     head(clean.omit[sample,]$NA_Sales)
     summary(boost.vg)
   })
```